name: ksad
description: 快手广告Flutter版本
version: 0.0.4
homepage: https://github.com/gstory0404/ksad

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
#  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.gstory.ksad
        pluginClass: KsadPlugin
      ios:
        pluginClass: KsadPlugin